### ISSUE TITLE
Implement Block SpGEMM

### ISSUE THREAD

**Issue by mzuzek** [fnrizzi/kokkos-kernels#29]
# TODO:

* [ ] Tests:
  - [x] simple explicit matrices with known multiplication result;
  - [x] implement block version of random matrix generator;
  - [ ] address regression test for [#402](https://github.com/kokkos/kokkos-kernels/issues/402): implement or drop.
* [ ] Interface: can we conveniently avoid separate `bspgemm` methods with proper templating over `spgemm` ?
* [ ] Address review feedback and tune performance;

## Implementation

* [x] Serial/Debug algorightm implementation (`SPGEMM_DEBUG`);
* [ ] Default algorithms Serial/Debug algorightm implementation (`SPGEMM_KK_MEMORY` and `SPGEMM_KK_MEMSPEED`);
  - [x] adjust hash accumulator for blocks;
  - [x] cover CPU variants: `MultiCoreTag` and `MultiCoreTag4`  (`SPGEMM_KK_LP`);
  - [ ] adjust memory estimation and algorithm/execution policy selection for block version;
    - [x] CPU (reduced to `suggested_vector_size`, `suggested_team_size`, and `team_row_chunk_size`);
    - [ ] GPU - detailed review of all estimations and allocations (+refactoring if possible).
  - [ ] GPU implementation;
  - [ ] Can we get unified accumulator (like `HashmapAccumulator` for non-block version);
* [ ] Connect TPLs for **performance** reference:
  - [x] _MKL_ for CPU benchmarking;
  - [ ] _CuSPARSE_ for GPU benchmarking;
* [ ] Speed numeric method: `SPGEMM_KK_SPEED`;
