### ISSUE TITLE
spmv product - high-level progress tracking [do not close]

### ISSUE THREAD

**Issue by fnrizzi** [fnrizzi/kokkos-kernels#8]
To keep track of the progress and get a bit more insights into how things are specialized/implemented. 
Checked boxes are those completed, unchecked is for things to do.

Public API: 
- [x] entry point for users 
        - The routine 'spmv' checks inside what is the extent of the input vector. Then it converts the input (multi-)vector into an object  `Kokkos::View<Scalar*, [...]>` or `Kokkos::View<Scalar**, [...]>`. Next the routine calls the appropriate function for the actual computation.
        - See [this file](https://github.com/fnrizzi/kokkos-kernels/blob/nga/14-block-storage/src/sparse/KokkosSparse_spmv.hpp) (if link is broken, it might be because of the wrong branch)

Backends: 
- [ ] Serial 
  - [x] single vector 
     - [x] Normal 
     - [x] Conjugate 
     - [x] Transpose 
     - [x] Hermitian 
  - [ ] multi vector 
     - [ ] Normal 
     - [ ] Conjugate 
     - [ ] Transpose 
     - [ ] Hermitian 
- [ ] OpenMP 
  - [x] single vector 
     - [x] Normal 
     - [x] Conjugate 
     - [x] Transpose 
     - [x] Hermitian 
  - [ ] multi vector 
     - [ ] Normal 
     - [ ] Conjugate 
     - [ ] Transpose 
     - [ ] Hermitian 
- [ ] Cuda
  - [x] single vector 
    - [x] fallback implementation that we write from scratch (needs to be tested)
    - [x] impl that uses native CUDA libraries (needs to be tested)
  - [ ] multi vector 
    - [ ] fallback implementation that we write from scratch 
    - [ ] impl that uses native CUDA libraries 
- [ ] others backends

Assumptions: 
- [x] matrix size is multiple of block size
       - The number of rows and columns for the actual matrix are multiple of the block size. Note that the functions `numRows()` and `numCols()` from `BlockCrsMatrix` return the rows for the `CrsGraph` object, which amounts to the number of blocks in the row dimension and the number of blocks in the column dimension. For example, if A is 6 x 8 with block size 2, the `CrsGraph` will have 3 rows and 4 columns. The function `BlockCrsMatrix::numRows()` will return 3 and `BlockCrsMatrix::numRows()` will return 4.
- [x] storage of numerical entries
       - The numerical values for the `BlockCrsMatrix` object is stored similarly to a `Tpetra` object. In particular, for a specific block in the matrix, the entries are stored in a row-order fashion in a contiguous memory space of dimension `blockDim_ * blockDim_`.
       -  !!! Note that this change has not been propagated to the file `KokkosSparse_BlockCrsMatrix.hpp` yet (as of June 16, 2021).
- [x] conversion from `CrsMatrix` to `BlockCrsMatrix`
      - The `CrsMatrix` object should store zero entries in a block to transmit the correct block structure.
- [ ] others?

Pending general issues
- [ ] whatever

**Comment by fnrizzi** [comment]
@uhetmaniuk based on how you are moving forward, it seems to me that this:
> The numerical values for the `BlockCrsMatrix` object is stored similarly to a `CrsMatrix` object. In particular, for a specific > block in the matrix, the entries are stored column-wise with a stride equal to the total number of non-zero entries on that ?> matrix row for accessing the next row in the block.

is no longer valid, right?
