### ISSUE TITLE
Provide general block spmv interface and specializations

### ISSUE THREAD

**Issue by mzuzek** [fnrizzi/kokkos-kernels#9]
* [x] Implement general `spmv()` interface that specializes for block and non-block crs inputs (matrix template).
     - [x] see issue #10  and PR #13
* [x] Explore specialization options templating on alpha, beta, N/T/C/H mode, etc. (similar to non-block `spmv()` - see the chart on https://github.com/fnrizzi/kokkos-kernels/issues/2#issuecomment-844152479):
  - [x] implement `Conjugate` where appropriate + include `std::complex` matrices in test samples (see follow up #27);
  - [x] add tests to cover corner cases (esp. alpha/beta=0/1/*) to existing N/T/C/H (note: no need for cross combining);
  - [X] split source files if helpful: 
       - [x] see issue #10 and PR #13
  - [x] check controls (e.g. `dynamic`/`static` schedule) implementation and supply missing items;
  - [x] fold block specializations (be careful about `blockSize=1` performance): PR #18
    * ~check if we can extract underlying crs matrix and run regular `spmv` for `blockSize=1`;~ moved to #28
